namespace Cc65DocsDbBuilder;

/// <summary>
/// A curated set of C64-Wiki (https://www.c64-wiki.com) articles - the hardware, memory layout,
/// graphics, KERNAL/BASIC and input topics a C64 programmer reaches for most - grouped the same way
/// <see cref="PageCatalog"/> groups the cc65 manuals. <see cref="PageEntry.FileName"/> is the page
/// id DocViewer shows and links by: <c>c64wiki/</c> plus the article's canonical MediaWiki page name
/// (spaces as underscores, e.g. <c>c64wiki/Memory_Map</c>), which is also its source file under
/// <c>SourceHtml/C64Wiki/</c> - see <see cref="MediaWikiHtmlToMarkdownConverter"/>.
///
/// C64-Wiki's content is licensed under the GNU Free Documentation License. The trailing
/// <see cref="LicencePageId"/> page, generated by the builder rather than converted from HTML,
/// carries what that licence asks of a redistributed copy: the licence notice and full text, and
/// for each article its title, its source and the specific revision it was taken from, whose
/// history on the wiki lists its authors.
/// </summary>
public static class C64WikiPageCatalog
{
    public const string PageIdPrefix = "c64wiki/";

    public const string LicencePageId = PageIdPrefix + "licence";

    public static readonly IReadOnlyList<PageCategory> Categories =
    [
        new PageCategory("The Machine",
        [
            new PageEntry("c64wiki/C64", "The Commodore 64 - history, models and specifications"),
            new PageEntry("c64wiki/MOS_Technology_6510", "The 6510 CPU and its on-chip I/O port"),
            new PageEntry("c64wiki/Commodore_1541", "The 1541 floppy disk drive"),
        ]),
        new PageCategory("Chips",
        [
            new PageEntry("c64wiki/VIC", "VIC-II video chip - registers, modes and timing"),
            new PageEntry("c64wiki/SID", "SID sound chip - voices, filters and registers"),
            new PageEntry("c64wiki/CIA", "CIA I/O chips - ports, timers and the time-of-day clock"),
        ]),
        new PageCategory("Memory",
        [
            new PageEntry("c64wiki/Memory_Map", "The C64 memory map"),
            new PageEntry("c64wiki/Zeropage", "Zero page usage by the KERNAL and BASIC"),
            new PageEntry("c64wiki/Bank_Switching", "Banking the ROMs and I/O in and out"),
            new PageEntry("c64wiki/Page_208-211", "The I/O area at $D000-$D3FF"),
            new PageEntry("c64wiki/Screen_RAM", "Screen memory"),
            new PageEntry("c64wiki/Color_RAM", "Color memory"),
        ]),
        new PageCategory("Graphics",
        [
            new PageEntry("c64wiki/Graphics_Modes", "Text and bitmap graphics modes"),
            new PageEntry("c64wiki/Sprite", "Hardware sprites"),
            new PageEntry("c64wiki/Raster_interrupt", "Raster interrupts"),
            new PageEntry("c64wiki/Character_set", "Character sets and custom characters"),
            new PageEntry("c64wiki/Color", "The 16-color palette"),
        ]),
        new PageCategory("Programming",
        [
            new PageEntry("c64wiki/Kernal", "The KERNAL ROM and its jump table"),
            new PageEntry("c64wiki/BASIC", "Commodore BASIC V2"),
            new PageEntry("c64wiki/PEEK", "BASIC's PEEK"),
            new PageEntry("c64wiki/POKE", "BASIC's POKE"),
            new PageEntry("c64wiki/Interrupt", "Interrupts (IRQ and NMI)"),
            new PageEntry("c64wiki/Opcode", "6502/6510 opcodes"),
            new PageEntry("c64wiki/PETSCII", "The PETSCII character encoding"),
        ]),
        new PageCategory("Input",
        [
            new PageEntry("c64wiki/Keyboard", "The keyboard and its matrix"),
            new PageEntry("c64wiki/Joystick", "Joysticks and the control ports"),
        ]),
        new PageCategory("Commodore PET",
        [
            new PageEntry("c64wiki/PET_2001", "The Commodore PET 2001 - models, hardware and history"),
            new PageEntry("c64wiki/IEEE-488", "IEEE-488, the PET's disk and printer bus"),
        ]),
        new PageCategory("Licence",
        [
            new PageEntry(LicencePageId, "C64-Wiki licence (GNU FDL), sources and revisions"),
        ]),
    ];

    /// <summary>Every page id, the generated licence page included.</summary>
    public static readonly IReadOnlySet<string> AllFileNames =
        Categories.SelectMany(c => c.Entries).Select(e => e.FileName).ToHashSet();

    /// <summary>The page ids converted from a C64-Wiki article (everything but the licence page).</summary>
    public static readonly IReadOnlyList<string> ArticlePageIds =
        Categories.SelectMany(c => c.Entries).Select(e => e.FileName).Where(id => id != LicencePageId).ToList();

    /// <summary>
    /// Redirect titles seen when these articles were fetched, mapped to the article they lead to -
    /// so a link to e.g. <c>/wiki/VIC-II</c> or <c>/wiki/Char</c> still lands on the bundled page.
    /// Keys and values are MediaWiki page names (underscores for spaces).
    /// </summary>
    public static readonly IReadOnlyDictionary<string, string> Redirects = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Commodore_64"] = "C64",
        ["6510"] = "MOS_Technology_6510",
        ["VIC-II"] = "VIC",
        ["Graphic_mode"] = "Graphics_Modes",
        ["Char"] = "Character_set",
        ["KERNAL"] = "Kernal",
        ["Commodore_PET"] = "PET_2001",
    };

    /// <summary>C64-Wiki as <see cref="MediaWikiHtmlToMarkdownConverter"/> sees it; no sections dropped.</summary>
    public static readonly MediaWikiSite Site = new(PageIdPrefix, Redirects, new HashSet<string>());
}
