using System.Text;
using System.Text.RegularExpressions;
using HtmlAgilityPack;

namespace Cc65DocsDbBuilder;

/// <summary>
/// Converts one chapter of the VICE manual (see <see cref="ViceManualPageCatalog"/>) to Markdown for
/// <c>Terminal.Gui.Views.Markdown</c>. The manual is generated by texi2html 1.52, so its HTML is old
/// and regular:
///
/// - A chapter's content lies between its two <c>&lt;HR&gt;</c>s; outside them is only the
///   "Go to the first, previous, next, last section, table of contents" navigation line.
/// - Headings are <c>&lt;Hn&gt;&lt;A NAME="SECnnn" HREF="vice_toc.html#TOCnnn"&gt;title&lt;/A&gt;&lt;/Hn&gt;</c>:
///   the <c>NAME</c> is the section's anchor, the <c>HREF</c> (back to the contents) is dropped.
///   H1 is the chapter title, so heading levels carry over as they are.
/// - Cross-references are <c>vice_N.html#SECnnn</c>. One into a bundled chapter becomes a page
///   link (<c>vice/binary_monitor.html#slug</c>, or <c>#slug</c> within the same chapter), resolved
///   through <see cref="BuildAnchorIndex"/>; one into a chapter not bundled keeps its text only.
/// - The manual marks options and commands with <c>&lt;DL&gt;</c> lists (a <c>&lt;DT&gt;</c> of
///   <c>&lt;CODE&gt;</c> per option), which become a bold term line followed by its description.
/// </summary>
public static partial class ViceManualHtmlToMarkdownConverter
{
    public sealed class PageAnchors
    {
        public required Dictionary<string, string> SlugsByAnchorName { get; init; }
    }

    /// <summary>Pass 1: each chapter's section anchors, mapped to the slug the viewer will give the
    /// heading they're on.</summary>
    public static Dictionary<string, PageAnchors> BuildAnchorIndex(IReadOnlyDictionary<string, string> htmlByPageId)
    {
        var index = new Dictionary<string, PageAnchors>();
        foreach (var (pageId, html) in htmlByPageId)
        {
            var slugUseCount = new Dictionary<string, int>();
            var slugsByAnchorName = new Dictionary<string, string>();
            foreach (var heading in Content(html).SelectMany(n => n.DescendantsAndSelf()).Where(IsHeading))
            {
                var text = FlattenText(heading);
                if (text.Length == 0)
                    continue;
                var slug = MarkdownSlug.MakeUnique(text, slugUseCount);
                foreach (var anchor in heading.Descendants("a").Select(a => a.GetAttributeValue("name", "")).Where(n => n.Length > 0))
                    slugsByAnchorName[anchor] = slug;
            }
            index[pageId] = new PageAnchors { SlugsByAnchorName = slugsByAnchorName };
        }
        return index;
    }

    /// <summary>Pass 2: the chapter as Markdown.</summary>
    public static string Convert(string html, string currentPageId, IReadOnlyDictionary<string, PageAnchors> anchorIndex)
    {
        var sb = new StringBuilder();
        var ctx = new Context(sb, currentPageId, anchorIndex);
        foreach (var node in Content(html))
            AppendNode(node, ctx);

        var text = sb.ToString();
        while (text.Contains("\n\n\n", StringComparison.Ordinal))
            text = text.Replace("\n\n\n", "\n\n", StringComparison.Ordinal);
        return text.Trim('\n') + "\n";
    }

    /// <summary>The chapter's content: the HTML between its first and last <c>&lt;HR&gt;</c>, parsed
    /// on its own - texi2html leaves the <c>&lt;P&gt;</c> around each <c>&lt;HR&gt;</c> unclosed, so
    /// cutting the text is more reliable than finding the rules in the parsed tree.</summary>
    private static IEnumerable<HtmlNode> Content(string html)
    {
        var first = html.IndexOf("<HR>", StringComparison.OrdinalIgnoreCase);
        var last = html.LastIndexOf("<HR>", StringComparison.OrdinalIgnoreCase);
        if (first < 0 || last <= first)
            throw new InvalidOperationException("Chapter doesn't have its two <HR> navigation separators.");

        var document = new HtmlDocument();
        document.LoadHtml(html[(first + "<HR>".Length)..last]);
        return document.DocumentNode.ChildNodes;
    }

    private sealed class Context(StringBuilder sb, string currentPageId, IReadOnlyDictionary<string, PageAnchors> anchorIndex)
    {
        public readonly StringBuilder Sb = sb;
        public readonly string CurrentPageId = currentPageId;
        public readonly IReadOnlyDictionary<string, PageAnchors> AnchorIndex = anchorIndex;
        public bool PendingSpace;
        public bool InCode;
        /// <summary>Set while rendering a definition term, which is bolded as a whole.</summary>
        public bool InBold;
        public int ListDepth;
    }

    private static bool IsHeading(HtmlNode node) => node.Name is "h1" or "h2" or "h3" or "h4" or "h5";

    private static void AppendChildren(HtmlNode node, Context ctx)
    {
        foreach (var child in node.ChildNodes)
            AppendNode(child, ctx);
    }

    private static void AppendNode(HtmlNode node, Context ctx)
    {
        if (node.NodeType == HtmlNodeType.Comment)
            return;

        if (node.NodeType == HtmlNodeType.Text)
        {
            var raw = HtmlEntity.DeEntitize(node.InnerText);
            var leadingSpace = raw.Length > 0 && char.IsWhiteSpace(raw[0]);
            var trailingSpace = raw.Length > 0 && char.IsWhiteSpace(raw[^1]);
            var collapsed = CollapseWhitespace(raw);
            if (collapsed.Length == 0)
            {
                if (raw.Length > 0)
                    ctx.PendingSpace = true;
                return;
            }
            if (ctx.Sb.Length > 0 && (leadingSpace || ctx.PendingSpace) && ctx.Sb[^1] is not ('\n' or ' '))
                ctx.Sb.Append(' ');
            ctx.Sb.Append(ctx.InCode ? collapsed : EscapeMarkdown(collapsed));
            ctx.PendingSpace = trailingSpace;
            return;
        }

        switch (node.Name)
        {
            case "head" or "title" or "style" or "script":
                return;

            case "a":
                AppendAnchor(ctx, node);
                return;

            case "h1" or "h2" or "h3" or "h4" or "h5":
            {
                var text = FlattenText(node);
                if (text.Length == 0)
                    return;
                EnsureBlankLine(ctx.Sb);
                ctx.Sb.Append(new string('#', node.Name[1] - '0')).Append(' ').Append(text).Append('\n');
                EnsureBlankLine(ctx.Sb);
                ctx.PendingSpace = false;
                return;
            }

            case "b" or "strong":
                if (ctx.InBold)
                    AppendChildren(node, ctx); // already inside a bolded term.
                else
                    WrapInline(ctx, node, "**", "**");
                return;

            case "i" or "em" or "var" or "cite" or "dfn":
                WrapInline(ctx, node, "*", "*");
                return;

            case "code" or "tt" or "kbd" or "samp":
                // texi2html nests <CODE><CODE>...</CODE></CODE>; wrap only the outermost.
                if (ctx.InCode)
                {
                    AppendChildren(node, ctx);
                    return;
                }
                ctx.InCode = true;
                WrapInline(ctx, node, "`", "`");
                ctx.InCode = false;
                return;

            case "p" or "div" or "center" or "blockquote":
                EnsureBlankLine(ctx.Sb);
                AppendChildren(node, ctx);
                EnsureBlankLine(ctx.Sb);
                return;

            case "br":
                ctx.Sb.Append("  \n");
                return;

            case "pre":
                EnsureBlankLine(ctx.Sb);
                ctx.Sb.Append("```\n").Append(HtmlEntity.DeEntitize(node.InnerText).Trim('\n', '\r')).Append("\n```\n");
                EnsureBlankLine(ctx.Sb);
                return;

            case "ul" or "ol" or "menu" or "dir":
                if (ctx.ListDepth == 0)
                    EnsureBlankLine(ctx.Sb);
                AppendListItems(ctx, node, ordered: node.Name == "ol");
                if (ctx.ListDepth == 0)
                    EnsureBlankLine(ctx.Sb);
                return;

            case "dl":
                EnsureBlankLine(ctx.Sb);
                AppendDefinitionList(ctx, node);
                EnsureBlankLine(ctx.Sb);
                return;

            case "table":
                EnsureBlankLine(ctx.Sb);
                AppendTable(ctx, node);
                EnsureBlankLine(ctx.Sb);
                return;

            default:
                AppendChildren(node, ctx);
                return;
        }
    }

    private static void WrapInline(Context ctx, HtmlNode node, string open, string close)
    {
        if (ctx.PendingSpace && ctx.Sb.Length > 0 && ctx.Sb[^1] is not ('\n' or ' '))
            ctx.Sb.Append(' ');
        ctx.PendingSpace = false;

        var startLength = ctx.Sb.Length;
        ctx.Sb.Append(open);
        AppendChildren(node, ctx);
        while (ctx.Sb.Length > startLength + open.Length && ctx.Sb[^1] == ' ')
        {
            ctx.Sb.Length--;
            ctx.PendingSpace = true;
        }
        if (ctx.Sb.Length == startLength + open.Length)
        {
            ctx.Sb.Length = startLength;
            return;
        }
        ctx.Sb.Append(close);
    }

    private static void AppendAnchor(Context ctx, HtmlNode node)
    {
        var url = ResolveHref(node.GetAttributeValue("href", ""), ctx.CurrentPageId, ctx.AnchorIndex);
        if (url is null)
        {
            AppendChildren(node, ctx);
            return;
        }

        if (ctx.PendingSpace && ctx.Sb.Length > 0 && ctx.Sb[^1] is not ('\n' or ' '))
            ctx.Sb.Append(' ');
        ctx.PendingSpace = false;

        ctx.Sb.Append('[');
        var startLength = ctx.Sb.Length;
        AppendChildren(node, ctx);
        if (ctx.Sb.Length == startLength)
        {
            ctx.Sb.Length--;
            return;
        }
        ctx.Sb.Append("](").Append(url).Append(')');
    }

    /// <summary>
    /// The DocViewer link for a manual <paramref name="href"/> (<c>vice_13.html#SEC349</c>), or null
    /// if it leads to a chapter that isn't bundled (or to the contents page). A section that can't be
    /// matched still links to its chapter.
    /// </summary>
    public static string? ResolveHref(string href, string currentPageId, IReadOnlyDictionary<string, PageAnchors> anchorIndex)
    {
        var match = ChapterHrefRegex().Match(href);
        if (!match.Success || ViceManualPageCatalog.PageIdFor(int.Parse(match.Groups["chapter"].Value)) is not { } pageId)
            return null;

        var anchor = match.Groups["anchor"].Value;
        var slug = anchor.Length > 0 && anchorIndex.TryGetValue(pageId, out var anchors)
            && anchors.SlugsByAnchorName.TryGetValue(anchor, out var s) ? s : null;
        if (pageId == currentPageId)
            return slug is null ? null : $"#{slug}";
        return slug is null ? $"{pageId}.html" : $"{pageId}.html#{slug}";
    }

    private static void AppendListItems(Context ctx, HtmlNode list, bool ordered)
    {
        var number = 1;
        var indent = new string(' ', 2 * ctx.ListDepth);
        foreach (var item in list.ChildNodes.Where(n => n.Name == "li"))
        {
            if (ctx.Sb.Length > 0 && ctx.Sb[^1] != '\n')
                ctx.Sb.Append('\n');
            ctx.Sb.Append(indent).Append(ordered ? $"{number++}. " : "- ");
            ctx.PendingSpace = false;
            foreach (var child in item.ChildNodes)
            {
                if (child.Name is "ul" or "ol")
                {
                    ctx.ListDepth++;
                    AppendNode(child, ctx);
                    ctx.ListDepth--;
                }
                else
                {
                    AppendNode(child, ctx);
                }
            }
            if (ctx.Sb.Length > 0 && ctx.Sb[^1] != '\n')
                ctx.Sb.Append('\n');
        }
    }

    private static void AppendDefinitionList(Context ctx, HtmlNode dl)
    {
        // texi2html leaves <DT>/<DD> unclosed, so HtmlAgilityPack may nest a DD's description (or
        // the next DT) inside it; walk them in document order instead of relying on the tree.
        foreach (var child in dl.ChildNodes)
        {
            if (child.Name == "dt")
            {
                // The term is rendered on its own, then trimmed and bolded as a whole: the manual's
                // terms are often <STRONG> already (which would double the markers) and start with
                // whitespace (which would stop "** text" being bold at all).
                EnsureNewLine(ctx.Sb);
                var startLength = ctx.Sb.Length;
                var wasInBold = ctx.InBold;
                ctx.InBold = true;
                ctx.PendingSpace = false;
                foreach (var part in child.ChildNodes.Where(n => n.Name is not ("dd" or "dt")))
                    AppendNode(part, ctx);
                ctx.InBold = wasInBold;
                var term = ctx.Sb.ToString(startLength, ctx.Sb.Length - startLength).Trim();
                ctx.Sb.Length = startLength;
                if (term.Length > 0)
                    ctx.Sb.Append("**").Append(term).Append("**\n");
                ctx.PendingSpace = false;
                foreach (var nested in child.ChildNodes.Where(n => n.Name is "dd" or "dt"))
                    AppendDefinitionPart(ctx, nested);
            }
            else if (child.Name == "dd")
            {
                AppendDefinitionPart(ctx, child);
            }
        }
        ctx.PendingSpace = false;
    }

    private static void AppendDefinitionPart(Context ctx, HtmlNode node)
    {
        if (node.Name == "dt")
        {
            var wrapper = HtmlNode.CreateNode("<dl></dl>");
            wrapper.AppendChild(node.CloneNode(true));
            AppendDefinitionList(ctx, wrapper);
            return;
        }
        EnsureNewLine(ctx.Sb);
        foreach (var part in node.ChildNodes)
            AppendNode(part, ctx);
        EnsureBlankLine(ctx.Sb);
        ctx.PendingSpace = false;
    }

    private static void AppendTable(Context ctx, HtmlNode table)
    {
        var rows = table.Descendants("tr")
            .Select(r => r.ChildNodes.Where(c => c.Name is "td" or "th").Select(c => CollapseWhitespace(HtmlEntity.DeEntitize(c.InnerText)).Trim().Replace("|", "\\|")).ToList())
            .Where(r => r.Count > 0)
            .ToList();
        if (rows.Count == 0)
            return;
        var columns = rows.Max(r => r.Count);
        for (var i = 0; i < rows.Count; i++)
        {
            ctx.Sb.Append("| ").Append(string.Join(" | ", rows[i].Concat(Enumerable.Repeat("", columns - rows[i].Count)))).Append(" |\n");
            if (i == 0)
                ctx.Sb.Append('|').Append(string.Concat(Enumerable.Repeat(" --- |", columns))).Append('\n');
        }
        ctx.PendingSpace = false;
    }

    private static string EscapeMarkdown(string text)
    {
        var sb = new StringBuilder(text.Length);
        foreach (var c in text)
        {
            if (c is '*' or '_' or '[' or ']' or '`' or '\\')
                sb.Append('\\');
            sb.Append(c);
        }
        return sb.ToString();
    }

    private static void EnsureNewLine(StringBuilder sb)
    {
        if (sb.Length > 0 && sb[^1] != '\n')
            sb.Append('\n');
    }

    private static void EnsureBlankLine(StringBuilder sb)
    {
        if (sb.Length == 0)
            return;
        if (sb[^1] != '\n')
            sb.Append('\n');
        if (sb.Length < 2 || sb[^2] != '\n')
            sb.Append('\n');
    }

    private static string FlattenText(HtmlNode node) =>
        CollapseWhitespace(HtmlEntity.DeEntitize(node.InnerText)).Trim();

    private static string CollapseWhitespace(string text) =>
        string.Join(' ', text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

    [GeneratedRegex(@"^vice_(?<chapter>\d+)\.html(?:#(?<anchor>[A-Za-z0-9_]+))?$", RegexOptions.IgnoreCase)]
    private static partial Regex ChapterHrefRegex();
}
