namespace Cc65DocsDbBuilder;

/// <summary>
/// Wikipedia articles on the Commodore PET and the chips and interfaces it (and cc65's other
/// Commodore targets) are built from - the hardware background C64-Wiki's PET coverage lacks. Page
/// ids are <c>wikipedia/</c> plus the article's canonical page name, which is also its source file
/// under <c>SourceHtml/Wikipedia/</c> (fetched through the MediaWiki API's parse action - see each
/// file's header for its revision). Converted by <see cref="MediaWikiHtmlToMarkdownConverter"/>.
///
/// Wikipedia's text is licensed under Creative Commons Attribution-ShareAlike 4.0. The trailing
/// <see cref="LicencePageId"/> page, generated by the builder, carries what that licence asks of a
/// redistributed copy: the licence and a link to it, each article's title and source, the revision
/// it was taken from (whose history lists its authors), and a note of what was changed.
/// </summary>
public static class WikipediaPageCatalog
{
    public const string PageIdPrefix = "wikipedia/";

    public const string LicencePageId = PageIdPrefix + "licence";

    public static readonly IReadOnlyList<PageCategory> Categories =
    [
        new PageCategory("Commodore PET",
        [
            new PageEntry("wikipedia/Commodore_PET", "The Commodore PET - models, hardware, software and history"),
            new PageEntry("wikipedia/Commodore_BASIC", "Commodore BASIC, from the PET's BASIC 1.0 to the C128's 7.0"),
            new PageEntry("wikipedia/PETSCII", "PETSCII, the character set that began on the PET"),
        ]),
        new PageCategory("Chips",
        [
            new PageEntry("wikipedia/MOS_Technology_6502", "The 6502 CPU - registers, addressing modes and instructions"),
            new PageEntry("wikipedia/Peripheral_Interface_Adapter", "The 6520/6820 PIA - the PET's keyboard and I/O ports"),
            new PageEntry("wikipedia/MOS_Technology_6522", "The 6522 VIA - ports, timers and shift register"),
            new PageEntry("wikipedia/Motorola_6845", "The 6845/6545 CRTC - the 80-column PETs' video controller"),
        ]),
        new PageCategory("Interfaces",
        [
            new PageEntry("wikipedia/GPIB", "IEEE-488 (GPIB), the PET's disk and printer bus"),
        ]),
        new PageCategory("Licence",
        [
            new PageEntry(LicencePageId, "Wikipedia licence (CC BY-SA 4.0), sources and revisions"),
        ]),
    ];

    /// <summary>Every page id, the generated licence page included.</summary>
    public static readonly IReadOnlySet<string> AllFileNames =
        Categories.SelectMany(c => c.Entries).Select(e => e.FileName).ToHashSet();

    /// <summary>The page ids converted from a Wikipedia article (everything but the licence page).</summary>
    public static readonly IReadOnlyList<string> ArticlePageIds =
        Categories.SelectMany(c => c.Entries).Select(e => e.FileName).Where(id => id != LicencePageId).ToList();

    /// <summary>
    /// Every redirect Wikipedia lists for these articles (queried when they were fetched), mapped to
    /// the article it leads to - so a link to e.g. <c>/wiki/IEEE-488</c> or <c>/wiki/6502</c> lands
    /// on the bundled page. Page names use underscores for spaces.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, string> Redirects = BuildRedirects(new Dictionary<string, string[]>
    {
        ["Commodore_PET"] = ["Commodore_pet", "PET_2001", "PET_computer", "Commodore_Pet", "Commodore_PET_2001", "SuperPET", "Commodore_SuperPET", "SuperPETs", "CBM_Model_4016", "Commodore_SP-9000"],
        ["Peripheral_Interface_Adapter"] = ["MOS_Technology_6520", "Peripheral_interface_adaptor"],
        ["MOS_Technology_6522"] = ["6522", "Versatile_Interface_Adapter"],
        ["Motorola_6845"] = ["MC6845", "MOS_Technology_6545", "6845", "CRTC6845", "6845_CRTC", "Motorola_MC6845", "M6845", "Motorola_6545", "HD46505"],
        ["GPIB"] = ["IEEE_488", "General-Purpose_Instrumentation_Bus", "General_Purpose_Instrumentation_Bus", "Hewlett-Packard_Instrumentation_Bus", "Hewlett_Packard_Instrumentation_Bus", "IEEE-488", "HP-IB", "IEEE-4888", "Hewlett-Packard_Interface_Bus", "GP-IB", "HPIB", "Ieee_448", "IEC_60488", "IEC_60625", "IEC-60488", "IEC-625", "General_Purpose_Interface", "IEEE488", "IEC-60625", "IEC_625", "General_Purpose_Interface_Bus"],
        ["Commodore_BASIC"] = ["Commodore_BASIC_programming_language", "CBM_BASIC", "BASIC_2.0", "BASIC_7.0", "PET_BASIC"],
        ["PETSCII"] = ["PET_ASCII", "CBM_ASCII", "PETASCII"],
        ["MOS_Technology_6502"] = ["MOS_Technology_6501", "MOS_Technology_65xx", "6502_microprocessor", "6502", "6501", "65xx", "MOS_Technologies_6501", "MOS_Technologies_6502", "MOS_Technologies_650x", "MOS_Technology_650x", "650x", "M6502", "MOS_6502", "Motorola_M6502", "6502_architecture_computer", "6502_Processor", "6502_assembly", "MOS_Technology_6502C", "MOS_6502C", "6502C", "MOS_6512", "6502A", "MOS_Technology_6512", "6502_processor", "MOS_6501", "MOS_Technology_6502A"],
    });

    /// <summary>Sections left out of every article: citation lists and outbound links, with nothing
    /// a reader can follow offline.</summary>
    public static readonly IReadOnlySet<string> DroppedSections = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "References", "Notes", "Citations", "Footnotes", "Sources", "Bibliography", "Further reading", "External links",
    };

    public static readonly MediaWikiSite Site = new(PageIdPrefix, Redirects, DroppedSections);

    /// <summary>Case-sensitive, like MediaWiki page names themselves (beyond their first letter) -
    /// "Commodore_pet" and "Commodore_Pet" are separate redirects.</summary>
    private static Dictionary<string, string> BuildRedirects(Dictionary<string, string[]> redirectsByArticle) =>
        redirectsByArticle
            .SelectMany(article => article.Value.Select(redirect => (redirect, article.Key)))
            .ToDictionary(p => p.redirect, p => p.Key, StringComparer.Ordinal);
}
