using System.Globalization;

namespace Tedide.Core.Debugging;

public sealed record DbgVersion(int Major, int Minor);

/// <summary>An input module (one compiled source file) - id and file id match <see cref="DbgFile.Files"/>.</summary>
public sealed record DbgModule(int Id, string Name, int File, int? Lib);

/// <summary>A file cc65 read while building this module - source, header, or assembler-generated
/// (.c/.h files list their own .s counterpart's id in <see cref="ModuleIds"/> too, since a module's
/// debug info is emitted against the assembly cl65 generated from the C source, not the C source
/// directly).</summary>
public sealed record DbgFileEntry(int Id, string Name, long Size, long MTime, IReadOnlyList<int> ModuleIds);

/// <summary>An address range within one output segment (<see cref="DbgFile.Segments"/>) - its
/// <see cref="Start"/>/<see cref="Size"/> are relative to that segment, not absolute; add
/// <see cref="DbgSegment.Start"/> to get an absolute address (see <see cref="DbgFile.FindAddressForSourceLine"/>).</summary>
public sealed record DbgSpan(int Id, int Seg, long Start, long Size);

/// <summary>One source line, optionally covering one or more <see cref="Spans"/> of generated code
/// - a line with no spans compiled to nothing (e.g. a declaration, a comment, an optimized-away
/// statement) and has no address to break on.</summary>
public sealed record DbgLine(int Id, int File, int Line, int Type, IReadOnlyList<int> Spans);

/// <summary>An output segment (CODE/RODATA/DATA/BSS/...), matching one of ld65's linker map
/// segments (<see cref="LinkerMapSegment"/>) but carrying debug-info-specific fields instead.</summary>
public sealed record DbgSegment(int Id, string Name, long Start, long Size, string AddrSize, string Type);

/// <summary>An assembly-level symbol - <see cref="Value"/> is null for an unresolved import
/// (<c>type=imp</c>), present for everything else.</summary>
public sealed record DbgSymbol(int Id, string Name, string AddrSize, int Scope, long? Value, int? Seg, string Type);

/// <summary>A lexical scope - a named function (<see cref="Type"/> <c>"scope"</c> with a non-empty
/// <see cref="Name"/>), an anonymous per-module scope (empty name, no <see cref="Type"/>), or a
/// struct/enum type definition (<see cref="Type"/> <c>"struct"</c>/<c>"enum"</c>). A function scope's
/// own <see cref="Spans"/> covers its *entire* compiled range (confirmed against a real build: its
/// size matches the corresponding <see cref="DbgSymbol"/>'s own size), unlike a <see cref="DbgLine"/>'s
/// much narrower per-statement span(s) - see <see cref="DbgFile.FindEnclosingFunctionName"/>.</summary>
public sealed record DbgScope(int Id, string Name, string? Type, int? Parent, IReadOnlyList<int> Spans);

/// <summary>
/// Parses cc65's debug info file (.dbg - written by ld65's <c>--dbgfile</c>, forwarded through cl65
/// via <c>-Wl --dbgfile,name</c> since cl65 itself has no top-level flag for it - see
/// <see cref="TedideProject.GenerateDebugInfo"/> and Cc65Toolchain.BuildLinkArguments). Each line is
/// one record: a tag word, a tab, then comma-separated <c>key=value</c> pairs (commas inside a
/// quoted string value don't end the field - see <see cref="SplitFields"/>); values are either a
/// quoted string, a bare identifier, a decimal or <c>0x</c>-prefixed hex number, or a
/// <c>+</c>-joined list of ids (e.g. <c>mod=0+1+2</c>, meaning "this file was read while building
/// modules 0, 1, and 2" - a header can be shared by several translation units).
///
/// Only the record types Tedide actually has a use for right now are modeled strongly
/// (<c>version</c>, <c>mod</c>, <c>file</c>, <c>span</c>, <c>line</c>, <c>seg</c>, <c>sym</c>,
/// <c>scope</c>) - captured against real files (tests/Tedide.Core.Tests/Fixtures/HelloCBM.dbg and
/// CBMInfo.dbg, generated by building those samples with -g), not guessed. <c>csym</c> (C-level
/// symbols/locals) exists in the format too but isn't parsed here since nothing in Tedide consumes
/// per-variable info yet - add it here, following the same pattern, if a future feature needs it.
/// </summary>
public sealed class DbgFile
{
    public DbgVersion Version { get; }
    public IReadOnlyList<DbgModule> Modules { get; }
    public IReadOnlyList<DbgFileEntry> Files { get; }
    public IReadOnlyList<DbgSpan> Spans { get; }
    public IReadOnlyList<DbgLine> Lines { get; }
    public IReadOnlyList<DbgSegment> Segments { get; }
    public IReadOnlyList<DbgSymbol> Symbols { get; }
    public IReadOnlyList<DbgScope> Scopes { get; }

    private DbgFile(
        DbgVersion version,
        IReadOnlyList<DbgModule> modules,
        IReadOnlyList<DbgFileEntry> files,
        IReadOnlyList<DbgSpan> spans,
        IReadOnlyList<DbgLine> lines,
        IReadOnlyList<DbgSegment> segments,
        IReadOnlyList<DbgSymbol> symbols,
        IReadOnlyList<DbgScope> scopes)
    {
        Version = version;
        Modules = modules;
        Files = files;
        Spans = spans;
        Lines = lines;
        Segments = segments;
        Symbols = symbols;
        Scopes = scopes;
    }

    public static DbgFile Parse(string text)
    {
        var version = new DbgVersion(0, 0);
        var modules = new List<DbgModule>();
        var files = new List<DbgFileEntry>();
        var spans = new List<DbgSpan>();
        var lines = new List<DbgLine>();
        var segments = new List<DbgSegment>();
        var symbols = new List<DbgSymbol>();
        var scopes = new List<DbgScope>();

        foreach (var rawLine in text.Replace("\r\n", "\n").Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(rawLine))
                continue;

            var tabIndex = rawLine.IndexOf('\t');
            if (tabIndex < 0)
                continue;

            var tag = rawLine[..tabIndex];
            var fields = SplitFields(rawLine[(tabIndex + 1)..]).ToDictionary(f => f.Key, f => f.Value);

            switch (tag)
            {
                case "version":
                    version = new DbgVersion(ParseInt(fields, "major"), ParseInt(fields, "minor"));
                    break;
                case "mod":
                    modules.Add(new DbgModule(
                        ParseInt(fields, "id"), fields["name"], ParseInt(fields, "file"), TryParseInt(fields, "lib")));
                    break;
                case "file":
                    files.Add(new DbgFileEntry(
                        ParseInt(fields, "id"), fields["name"], ParseNumber(fields, "size"), ParseNumber(fields, "mtime"),
                        ParseIntList(fields, "mod")));
                    break;
                case "span":
                    spans.Add(new DbgSpan(
                        ParseInt(fields, "id"), ParseInt(fields, "seg"), ParseNumber(fields, "start"), ParseNumber(fields, "size")));
                    break;
                case "line":
                    lines.Add(new DbgLine(
                        ParseInt(fields, "id"), ParseInt(fields, "file"), ParseInt(fields, "line"),
                        TryParseInt(fields, "type") ?? 0, ParseIntList(fields, "span")));
                    break;
                case "seg":
                    segments.Add(new DbgSegment(
                        ParseInt(fields, "id"), fields["name"], ParseNumber(fields, "start"), ParseNumber(fields, "size"),
                        fields.GetValueOrDefault("addrsize", ""), fields.GetValueOrDefault("type", "")));
                    break;
                case "sym":
                    symbols.Add(new DbgSymbol(
                        ParseInt(fields, "id"), fields["name"], fields.GetValueOrDefault("addrsize", ""),
                        TryParseInt(fields, "scope") ?? 0,
                        fields.TryGetValue("val", out var val) ? ParseNumber(val) : null,
                        TryParseInt(fields, "seg"), fields.GetValueOrDefault("type", "")));
                    break;
                case "scope":
                    scopes.Add(new DbgScope(
                        ParseInt(fields, "id"), fields.GetValueOrDefault("name", ""),
                        fields.GetValueOrDefault("type"), TryParseInt(fields, "parent"), ParseIntList(fields, "span")));
                    break;
            }
        }

        return new DbgFile(version, modules, files, spans, lines, segments, symbols, scopes);
    }

    /// <summary>
    /// Resolves a source line to an absolute address (file's own <see cref="DbgSpan"/>, offset by
    /// its segment's start), for setting a breakpoint at that line. Matches <paramref name="sourceFilePath"/>
    /// against <see cref="Files"/> by exact match first, falling back to a bare filename match (a
    /// .dbg file's own path is relative to wherever cl65 was invoked, which may not exactly match
    /// how the caller names the same file - see this method's own callers for what they pass).
    /// Returns null if the file isn't found, the line has no compiled code (no spans - e.g. a
    /// declaration or an optimized-away statement), or a span/segment id it references is missing.
    /// </summary>
    public long? FindAddressForSourceLine(string sourceFilePath, int lineNumber)
    {
        var file = Files.FirstOrDefault(f => string.Equals(f.Name, sourceFilePath, StringComparison.OrdinalIgnoreCase))
            ?? Files.FirstOrDefault(f => string.Equals(Path.GetFileName(f.Name), Path.GetFileName(sourceFilePath), StringComparison.OrdinalIgnoreCase));
        if (file is null)
            return null;

        var line = Lines.FirstOrDefault(l => l.File == file.Id && l.Line == lineNumber && l.Spans.Count > 0);
        if (line is null)
            return null;

        var span = Spans.FirstOrDefault(s => s.Id == line.Spans[0]);
        if (span is null)
            return null;

        var segment = Segments.FirstOrDefault(s => s.Id == span.Seg);
        return segment is null ? null : segment.Start + span.Start;
    }

    /// <summary>
    /// Resolves an absolute address back to a source file/line, for highlighting where execution is
    /// currently stopped. Returns null if the address falls outside every known segment/span, or the
    /// matching span isn't referenced by any line record.
    /// </summary>
    public (string FilePath, int Line)? FindSourceLocationForAddress(long address)
    {
        foreach (var segment in Segments)
        {
            if (address < segment.Start || address >= segment.Start + segment.Size)
                continue;

            var offsetInSegment = address - segment.Start;
            // More than one span can legitimately match the same address: cc65 emits a coarse span
            // covering a whole C statement (paired with a .c line record) that can fully overlap a
            // narrower .s-only span nested inside it for compiler-generated glue (e.g. a function's
            // prologue) - confirmed against a real build of samples/CBMInfo: at offset 154, span 108
            // ("src/main.s", 2 bytes, .s-only) and span 116 ("src/main.c", 21 bytes) both match.
            // Picking only the first (narrowest/lowest-id) span, as a single Spans.FirstOrDefault
            // would, can land on the .s-only one even though a wider .c-paired span also covers this
            // exact address. Check every matching span and prefer whichever ultimately resolves to a
            // non-assembly file.
            var matchingSpans = Spans.Where(s =>
                s.Seg == segment.Id && offsetInSegment >= s.Start && offsetInSegment < s.Start + s.Size);

            (string FilePath, int Line)? assemblyFallback = null;
            foreach (var span in matchingSpans)
            {
                // A span compiled from C source can also carry TWO line records against the exact
                // same code: one against cl65's own generated .s intermediate and one against the
                // original .c/.h - confirmed against tests/Tedide.Core.Tests/Fixtures/HelloCBM.dbg,
                // where span 7 has both "file=0 (src/main.s), line=62" and "file=2 (src/main.c),
                // line=26". Prefer any non-assembly candidate here too; fall back to assembly only
                // when that's genuinely the only source for this span (a hand-written .s file with
                // no C counterpart, e.g. HelloCBM's border.s, which has its own module and no paired
                // .c line record for its spans).
                var candidates = Lines.Where(l => l.Spans.Contains(span.Id)).ToList();
                var line = candidates.FirstOrDefault(l => !IsAssemblyFile(l.File)) ?? candidates.FirstOrDefault();
                if (line is null)
                    continue;

                var file = Files.FirstOrDefault(f => f.Id == line.File);
                if (file is null)
                    continue;

                if (!IsAssemblyFile(line.File))
                    return (file.Name, line.Line);

                assemblyFallback ??= (file.Name, line.Line);
            }

            if (assemblyFallback is { } fallback)
                return fallback;
        }

        return null;
    }

    /// <summary>
    /// Resolves an absolute address to the name of the enclosing named function, for showing e.g.
    /// "Stopped in detect_system at ..." rather than just a bare file/line. Returns null if the
    /// address falls outside every function scope - notably, code with no debug info at all (e.g.
    /// cc65's own runtime library, which has no <c>scope</c> records for its own routines).
    /// </summary>
    public string? FindEnclosingFunctionName(long address)
    {
        foreach (var scope in Scopes)
        {
            // Anonymous per-module scopes (id=0-ish, empty name, no "type" field) and struct/enum
            // type definitions ("type=struct") aren't functions - only a named "type=scope" record
            // is, confirmed against a real build: e.g. `scope id=1,name="_detect_system",mod=0,
            // type=scope,size=127,parent=0,sym=24,span=93` vs. the file-level
            // `scope id=0,name="",mod=0,size=435,span=29+230+229` it's nested under.
            if (scope.Type != "scope" || string.IsNullOrEmpty(scope.Name))
                continue;

            foreach (var spanId in scope.Spans)
            {
                var span = Spans.FirstOrDefault(s => s.Id == spanId);
                if (span is null)
                    continue;

                var segment = Segments.FirstOrDefault(s => s.Id == span.Seg);
                if (segment is null)
                    continue;

                var absoluteStart = segment.Start + span.Start;
                if (address >= absoluteStart && address < absoluteStart + span.Size)
                    // cc65 prefixes every C-level symbol with "_" for the assembler - strip it to
                    // show the name as it appears in the actual C source.
                    return scope.Name.TrimStart('_');
            }
        }

        return null;
    }

    private bool IsAssemblyFile(int fileId)
    {
        var extension = Path.GetExtension(Files.FirstOrDefault(f => f.Id == fileId)?.Name);
        return string.Equals(extension, ".s", StringComparison.OrdinalIgnoreCase)
            || string.Equals(extension, ".asm", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Splits a record's comma-separated <c>key=value</c> fields, treating commas inside a
    /// double-quoted value (e.g. a file path) as part of that value rather than a field separator.
    /// Quotes themselves are stripped from the returned value.
    /// </summary>
    private static IEnumerable<(string Key, string Value)> SplitFields(string fieldsText)
    {
        var start = 0;
        var inQuotes = false;
        for (var i = 0; i <= fieldsText.Length; i++)
        {
            var atEnd = i == fieldsText.Length;
            if (!atEnd && fieldsText[i] == '"')
                inQuotes = !inQuotes;

            if (atEnd || (fieldsText[i] == ',' && !inQuotes))
            {
                var field = fieldsText[start..i];
                var eq = field.IndexOf('=');
                if (eq > 0)
                {
                    var value = field[(eq + 1)..];
                    if (value.Length >= 2 && value[0] == '"' && value[^1] == '"')
                        value = value[1..^1];
                    yield return (field[..eq], value);
                }
                start = i + 1;
            }
        }
    }

    private static int ParseInt(Dictionary<string, string> fields, string key) => int.Parse(fields[key], CultureInfo.InvariantCulture);

    private static int? TryParseInt(Dictionary<string, string> fields, string key) =>
        fields.TryGetValue(key, out var value) ? int.Parse(value, CultureInfo.InvariantCulture) : null;

    private static long ParseNumber(Dictionary<string, string> fields, string key) => ParseNumber(fields[key]);

    private static long ParseNumber(string value) => value.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
        ? Convert.ToInt64(value[2..], 16)
        : long.Parse(value, CultureInfo.InvariantCulture);

    private static IReadOnlyList<int> ParseIntList(Dictionary<string, string> fields, string key) =>
        fields.TryGetValue(key, out var value)
            ? value.Split('+').Select(v => int.Parse(v, CultureInfo.InvariantCulture)).ToList()
            : [];
}
