using System.Globalization;
using System.Text.RegularExpressions;

namespace Tedide.Core;

/// <summary>A cc65 segment inside one module, as it appears under that module's own header line
/// in the "Modules list:" section (e.g. "    CODE  Offs=000016  Size=00004B  Align=00001  Fill=0000").</summary>
public sealed record LinkerMapModuleSegment(string Name, long Offset, long Size, int Align, int Fill);

/// <summary>One input module (an object file, or "archive.lib(module.o)" for a library member) from
/// ld65's linker map "Modules list:" section. A module can have zero segments (e.g. a library
/// member that contributed only symbols, no code/data of its own).</summary>
public sealed record LinkerMapModule(string Name, IReadOnlyList<LinkerMapModuleSegment> Segments, int MapFileLineNumber);

/// <summary>One row of ld65's linker map "Segment list:" table - an output segment's address range.</summary>
public sealed record LinkerMapSegment(string Name, long Start, long End, long Size, int Align, int MapFileLineNumber);

/// <summary>One exported symbol from ld65's linker map "Exports list by name:" section (the "by
/// value" section right after it is the same export set sorted by address instead of name, so it's
/// not modeled separately here - see <see cref="LinkerMapFile.Parse"/>).</summary>
public sealed record LinkerMapExport(string Name, long Value, string Flags, int MapFileLineNumber);

/// <summary>One place an imported symbol was referenced from, under that symbol's own header line
/// in the "Imports list:" section (e.g. "    crt0.o                    c64/crt0.s:10" - or, for a
/// symbol the linker itself defines/references rather than any object file,
/// "    [linker generated]        C:\CC65\CFG/c64.cfg:6").</summary>
public sealed record LinkerMapImportReference(string Module, string File, int Line);

/// <summary>One symbol from ld65's linker map "Imports list:" section, referenced by one or more
/// object files (or the linker itself).</summary>
public sealed record LinkerMapImport(string SymbolName, string DefiningModule, IReadOnlyList<LinkerMapImportReference> References, int MapFileLineNumber);

/// <summary>
/// Parses ld65's linker map (lnk.map - see <see cref="TedideProject.ResolvedMapFile"/>) into its
/// four sections: Modules list, Segment list, Exports list (by name only - "by value" is the same
/// set sorted differently, so it's skipped rather than modeled twice), and Imports list. Feeds
/// Tedide's symbol panel (see Tedide.App's SymbolPanelView) so a user can browse/search a build's
/// segments and symbols instead of reading the raw text file. Every record carries its own 1-based
/// <c>MapFileLineNumber</c> so the panel can jump the editor straight to it.
///
/// The exact column layout parsed here (module segment lines' Offs=/Size=/Align=/Fill= fields, the
/// two-exports-per-80-column-line layout of the Exports sections, and the 4-space-indent + 26-char
/// module field of Imports reference lines) was captured from a real build (see
/// tests/Tedide.Core.Tests/Fixtures/HelloCBM.lnk.map, generated by building samples/HelloCBM with
/// -m) rather than guessed - not a full grammar, but tolerant of the two things that vary between
/// builds: how many segments a module has (zero is valid - e.g. a library member that only
/// contributed symbols) and how many places an imported symbol is referenced from.
/// </summary>
public sealed class LinkerMapFile
{
    public IReadOnlyList<LinkerMapModule> Modules { get; }
    public IReadOnlyList<LinkerMapSegment> Segments { get; }
    public IReadOnlyList<LinkerMapExport> Exports { get; }
    public IReadOnlyList<LinkerMapImport> Imports { get; }

    private LinkerMapFile(
        IReadOnlyList<LinkerMapModule> modules,
        IReadOnlyList<LinkerMapSegment> segments,
        IReadOnlyList<LinkerMapExport> exports,
        IReadOnlyList<LinkerMapImport> imports)
    {
        Modules = modules;
        Segments = segments;
        Exports = exports;
        Imports = imports;
    }

    private enum Section { None, Modules, Segments, ExportsByName, Skip, Imports }

    private static readonly Regex ModuleHeaderRegex = new(@"^(\S.*):$", RegexOptions.Compiled);
    private static readonly Regex ModuleSegmentRegex = new(
        @"^\s+(\S+)\s+Offs=([0-9A-Fa-f]+)\s+Size=([0-9A-Fa-f]+)\s+Align=([0-9A-Fa-f]+)\s+Fill=([0-9A-Fa-f]+)\s*$",
        RegexOptions.Compiled);
    private static readonly Regex SegmentLineRegex = new(
        @"^(\S+)\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s*$",
        RegexOptions.Compiled);
    private static readonly Regex ExportEntryRegex = new(@"(\S+)\s+([0-9A-Fa-f]{6})\s+([A-Z]{3})", RegexOptions.Compiled);
    private static readonly Regex ImportHeaderRegex = new(@"^(\S+) \((.+)\):$", RegexOptions.Compiled);
    private static readonly Regex ImportReferenceRegex = new(@"^\s{4}(\S.*?)\s{2,}(\S.*)$", RegexOptions.Compiled);
    private static readonly Regex FileLineRegex = new(@"^(.*):(\d+)$", RegexOptions.Compiled);

    public static LinkerMapFile Parse(string text)
    {
        var modules = new List<LinkerMapModule>();
        var segments = new List<LinkerMapSegment>();
        var exports = new List<LinkerMapExport>();
        var imports = new List<LinkerMapImport>();

        var lines = text.Replace("\r\n", "\n").Split('\n');
        var section = Section.None;
        List<LinkerMapModuleSegment>? currentModuleSegments = null;
        List<LinkerMapImportReference>? currentImportReferences = null;

        for (var i = 0; i < lines.Length; i++)
        {
            var raw = lines[i];
            var trimmed = raw.TrimEnd('\r');

            if (trimmed == "Modules list:") { section = Section.Modules; i++; continue; }
            if (trimmed == "Segment list:") { section = Section.Segments; i += 3; continue; } // dash line, column header, dash line
            if (trimmed == "Exports list by name:") { section = Section.ExportsByName; i++; continue; }
            if (trimmed == "Exports list by value:") { section = Section.Skip; i++; continue; }
            if (trimmed == "Imports list:") { section = Section.Imports; i++; continue; }

            if (string.IsNullOrWhiteSpace(trimmed))
                continue;

            switch (section)
            {
                case Section.Modules:
                    var moduleMatch = ModuleHeaderRegex.Match(trimmed);
                    if (moduleMatch.Success)
                    {
                        currentModuleSegments = [];
                        modules.Add(new LinkerMapModule(moduleMatch.Groups[1].Value, currentModuleSegments, i + 1));
                    }
                    else if (currentModuleSegments is not null)
                    {
                        var segMatch = ModuleSegmentRegex.Match(trimmed);
                        if (segMatch.Success)
                        {
                            currentModuleSegments.Add(new LinkerMapModuleSegment(
                                segMatch.Groups[1].Value,
                                ParseHex(segMatch.Groups[2].Value),
                                ParseHex(segMatch.Groups[3].Value),
                                (int)ParseHex(segMatch.Groups[4].Value),
                                (int)ParseHex(segMatch.Groups[5].Value)));
                        }
                    }
                    break;

                case Section.Segments:
                    var segLineMatch = SegmentLineRegex.Match(trimmed);
                    if (segLineMatch.Success)
                    {
                        segments.Add(new LinkerMapSegment(
                            segLineMatch.Groups[1].Value,
                            ParseHex(segLineMatch.Groups[2].Value),
                            ParseHex(segLineMatch.Groups[3].Value),
                            ParseHex(segLineMatch.Groups[4].Value),
                            (int)ParseHex(segLineMatch.Groups[5].Value),
                            i + 1));
                    }
                    break;

                case Section.ExportsByName:
                    foreach (Match m in ExportEntryRegex.Matches(trimmed))
                    {
                        exports.Add(new LinkerMapExport(
                            m.Groups[1].Value,
                            ParseHex(m.Groups[2].Value),
                            m.Groups[3].Value,
                            i + 1));
                    }
                    break;

                case Section.Imports:
                    var importHeaderMatch = ImportHeaderRegex.Match(trimmed);
                    if (importHeaderMatch.Success)
                    {
                        currentImportReferences = [];
                        imports.Add(new LinkerMapImport(
                            importHeaderMatch.Groups[1].Value,
                            importHeaderMatch.Groups[2].Value,
                            currentImportReferences,
                            i + 1));
                    }
                    else if (currentImportReferences is not null)
                    {
                        var refMatch = ImportReferenceRegex.Match(trimmed);
                        if (refMatch.Success)
                        {
                            var fileLineMatch = FileLineRegex.Match(refMatch.Groups[2].Value);
                            if (fileLineMatch.Success)
                            {
                                currentImportReferences.Add(new LinkerMapImportReference(
                                    refMatch.Groups[1].Value,
                                    fileLineMatch.Groups[1].Value,
                                    int.Parse(fileLineMatch.Groups[2].Value, CultureInfo.InvariantCulture)));
                            }
                        }
                    }
                    break;

                case Section.None:
                case Section.Skip:
                    break;
            }
        }

        return new LinkerMapFile(modules, segments, exports, imports);
    }

    private static long ParseHex(string hex) => Convert.ToInt64(hex, 16);
}
