"""Generates sim65/regs.s: calls every helper in RuntimeHelpers.cs's table inside a loop, 256
times with varied A/X/Y/carry, sp low byte (so every page-crossing path runs) and memory, and folds
A, X, Y, the flags, sp, the stack window, a buffer and the zero-page temps into a checksum after
each call. run_sim65_tests.sh runs it with the real library helpers and with opt6502 -speed's
inlined copies; the checksums must match. Regenerate with: python sim65/gen_regs.py"""
import os

# name -> setup kind. "value": A/X/Y are plain values. "ptr": A/X point into buf (ldaxidx family).
# "tospointer": top of C stack holds a pointer into buf (staxspidx). "laddeq": ptr1 low / Y high
# address a long in buf, A/X/sreg the value.
HELPERS = {
    **{n: "value" for n in """pushax pusha0 push0 pusha decsp1 decsp2 decsp3 decsp4 decsp5 decsp6 decsp7
        decsp8 incsp1 incsp2 addysp addysp1 incsp3 incsp4 incsp5 incsp6 incsp7 incsp8 ldaxysp ldax0sp
        staxysp stax0sp pushwysp pushw0sp addeqysp addeq0sp subeqysp subeq0sp leaaxsp leaa0sp tosicmp
        tosicmp0 incax2 incaxy incax3 incax4 incax5 incax6 incax7 incax8 aslax1 shlax1 aslax2 shlax2
        mulax3 mulax5 mulax9""".split()},
    "ldaxidx": "ptr", "ldaxi": "ptr",
    "staxspidx": "tospointer",
    "laddeq": "laddeq", "laddeqa": "laddeq", "laddeq1": "laddeq",
}

HEADER = """; Generated by gen_regs.py - see there. Written in cc65's output style (the header lines below
; are what RuntimeInliner checks for) so opt6502 -speed treats it as cc65 2.19 output.
\t.fopt\t\tcompiler,"cc65 v 2.19 - Git b75f872"
\t.setcpu\t\t"6502"
\t.smart\t\ton
\t.autoimport\ton
\t.case\t\ton
\t.importzp\tsp, sreg, regsave, regbank
\t.importzp\ttmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
\t.macpack\tlongbranch
\t.export\t\t_main

STACKPAGE = $90          ; C stack moved to $9000+cnt for each call: sp low byte takes every value
buf = $9400              ; fixed, like the stack: pointers into it are folded into the checksum,
                         ; and inlining changes code size, which would move anything in BSS

.segment\t"BSS"
cnt:\t.res\t1
chk:\t.res\t3
sp0:\t.res\t2

.segment\t"RODATA"
fmt:\t.byte\t"%lu", $0A, $00

.segment\t"CODE"

; Registers and memory for call number cnt. Leaves carry = bit 0 of cnt; kind picks A/X/Y.
.proc\tsetup: near
\tlda\tcnt
\tsta\tsp
\tlda\t#STACKPAGE
\tsta\tsp+1
\tldy\t#0              ; fill $8Fxx..$90xx+16 around sp with a cnt-dependent pattern
@fill:\ttya
\teor\tcnt
\tasl\ta
\tadc\tcnt
\tsta\t$8F00+128,y
\tsta\t$9000,y
\tsta\t$9100,y
\tiny
\tbne\t@fill
\tldy\t#63
@buf:\ttya
\teor\tcnt
\tsta\tbuf,y
\tdey
\tbpl\t@buf
\tlda\tcnt
\teor\t#$A5
\tsta\tsreg
\tasl\ta
\tsta\tsreg+1
\trts
.endproc

; Folds one byte (A) into the 24-bit rotating checksum.
.proc\tfoldbyte: near
\teor\tchk
\tsta\tchk
\tasl\tchk
\trol\tchk+1
\trol\tchk+2
\tbcc\t@done
\tinc\tchk
@done:\trts
.endproc

; Folds the flags (captured first), A, X, Y, sp, the stack window, buf and the zero-page temps.
.proc\tfold: near
\tphp
\tpha
\ttxa
\tpha
\ttya
\tjsr\tfoldbyte
\tpla
\tjsr\tfoldbyte           ; X
\tpla
\tjsr\tfoldbyte           ; A
\tpla
\tjsr\tfoldbyte           ; P
\tlda\tsp
\tjsr\tfoldbyte
\tlda\tsp+1
\tjsr\tfoldbyte
\tldy\t#0
@stack:\tlda\t$9000,y
\tjsr\tfoldbyte
\tlda\t$8F00+128,y
\tjsr\tfoldbyte
\tlda\t$9100,y
\tjsr\tfoldbyte
\tiny
\tbne\t@stack
\tldy\t#63
@buf:\tlda\tbuf,y
\tjsr\tfoldbyte
\tdey
\tbpl\t@buf
\tlda\tsreg
\tjsr\tfoldbyte
\tlda\tsreg+1
\tjsr\tfoldbyte
\tlda\ttmp1
\tjsr\tfoldbyte
\tlda\tptr1
\tjsr\tfoldbyte
\tlda\tptr1+1
\tjsr\tfoldbyte
\trts
.endproc

.proc\t_main: near
\tlda\tsp
\tsta\tsp0
\tlda\tsp+1
\tsta\tsp0+1
\tlda\t#0
\tsta\tchk
\tsta\tchk+1
\tsta\tchk+2
"""

SETUP = {
    # A = cnt, X = cnt*3 (varied high byte), Y = 1..7 odd (in the filled window), carry = bit 0
    "value": ["jsr     setup", "lda     cnt", "asl     a", "adc     cnt", "tax",
              "lda     cnt", "and     #6", "ora     #1", "tay", "lda     cnt", "lsr     a", "lda     cnt"],
    "ptr": ["jsr     setup", "lda     cnt", "and     #31", "clc", "adc     #<buf", "pha", "lda     #0",
            "adc     #>buf", "tax", "lda     cnt", "and     #6", "ora     #1", "tay", "pla"],
    "tospointer": ["jsr     setup", "lda     cnt", "and     #31", "clc", "adc     #<buf", "ldy     #0",
                   "sta     (sp),y", "lda     #0", "adc     #>buf", "iny", "sta     (sp),y",
                   "lda     cnt", "and     #6", "tay", "lda     cnt", "asl     a", "tax", "lda     cnt"],
    "laddeq": ["jsr     setup", "lda     cnt", "and     #28", "clc", "adc     #<buf", "sta     ptr1",
               "lda     #0", "adc     #>buf", "tay", "lda     cnt", "asl     a", "tax", "lda     cnt"],
}

def main():
    out = [HEADER]
    for i, (name, kind) in enumerate(HELPERS.items()):
        out.append(f"; --- {name}")
        out.append("\tlda     #0")
        out.append("\tsta     cnt")
        out.append(f"L{i:04X}:")
        out.extend("\t" + line for line in SETUP[kind])
        out.append(f"\tjsr     {name}")
        out.append("\tjsr     fold")
        out.append("\tinc     cnt")
        out.append(f"\tjne     L{i:04X}")
    out.append("""; restore the real C stack and print the checksum
\tlda\tsp0
\tsta\tsp
\tlda\tsp0+1
\tsta\tsp+1
\tlda\t#<fmt
\tldx\t#>fmt
\tjsr\tpushax
\tlda\tchk+2
\tsta\tsreg
\tlda\t#0
\tsta\tsreg+1
\tlda\tchk
\tldx\tchk+1
\tjsr\tpusheax
\tldy\t#6
\tjsr\t_printf
\tlda\tchk
\tand\t#$7F
\tldx\t#0
\trts
.endproc
""")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "regs.s")
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {path}: {len(HELPERS)} helpers")

if __name__ == "__main__":
    main()
