; Generated by gen_regs.py - see there. Written in cc65's output style (the header lines below
; are what RuntimeInliner checks for) so opt6502 -speed treats it as cc65 2.19 output.
	.fopt		compiler,"cc65 v 2.19 - Git b75f872"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_main

STACKPAGE = $90          ; C stack moved to $9000+cnt for each call: sp low byte takes every value
buf = $9400              ; fixed, like the stack: pointers into it are folded into the checksum,
                         ; and inlining changes code size, which would move anything in BSS

.segment	"BSS"
cnt:	.res	1
chk:	.res	3
sp0:	.res	2

.segment	"RODATA"
fmt:	.byte	"%lu", $0A, $00

.segment	"CODE"

; Registers and memory for call number cnt. Leaves carry = bit 0 of cnt; kind picks A/X/Y.
.proc	setup: near
	lda	cnt
	sta	sp
	lda	#STACKPAGE
	sta	sp+1
	ldy	#0              ; fill $8Fxx..$90xx+16 around sp with a cnt-dependent pattern
@fill:	tya
	eor	cnt
	asl	a
	adc	cnt
	sta	$8F00+128,y
	sta	$9000,y
	sta	$9100,y
	iny
	bne	@fill
	ldy	#63
@buf:	tya
	eor	cnt
	sta	buf,y
	dey
	bpl	@buf
	lda	cnt
	eor	#$A5
	sta	sreg
	asl	a
	sta	sreg+1
	rts
.endproc

; Folds one byte (A) into the 24-bit rotating checksum.
.proc	foldbyte: near
	eor	chk
	sta	chk
	asl	chk
	rol	chk+1
	rol	chk+2
	bcc	@done
	inc	chk
@done:	rts
.endproc

; Folds the flags (captured first), A, X, Y, sp, the stack window, buf and the zero-page temps.
.proc	fold: near
	php
	pha
	txa
	pha
	tya
	jsr	foldbyte
	pla
	jsr	foldbyte           ; X
	pla
	jsr	foldbyte           ; A
	pla
	jsr	foldbyte           ; P
	lda	sp
	jsr	foldbyte
	lda	sp+1
	jsr	foldbyte
	ldy	#0
@stack:	lda	$9000,y
	jsr	foldbyte
	lda	$8F00+128,y
	jsr	foldbyte
	lda	$9100,y
	jsr	foldbyte
	iny
	bne	@stack
	ldy	#63
@buf:	lda	buf,y
	jsr	foldbyte
	dey
	bpl	@buf
	lda	sreg
	jsr	foldbyte
	lda	sreg+1
	jsr	foldbyte
	lda	tmp1
	jsr	foldbyte
	lda	ptr1
	jsr	foldbyte
	lda	ptr1+1
	jsr	foldbyte
	rts
.endproc

.proc	_main: near
	lda	sp
	sta	sp0
	lda	sp+1
	sta	sp0+1
	lda	#0
	sta	chk
	sta	chk+1
	sta	chk+2

; --- pushax
	lda     #0
	sta     cnt
L0000:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     pushax
	jsr     fold
	inc     cnt
	jne     L0000
; --- pusha0
	lda     #0
	sta     cnt
L0001:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     pusha0
	jsr     fold
	inc     cnt
	jne     L0001
; --- push0
	lda     #0
	sta     cnt
L0002:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     push0
	jsr     fold
	inc     cnt
	jne     L0002
; --- pusha
	lda     #0
	sta     cnt
L0003:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     pusha
	jsr     fold
	inc     cnt
	jne     L0003
; --- decsp1
	lda     #0
	sta     cnt
L0004:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp1
	jsr     fold
	inc     cnt
	jne     L0004
; --- decsp2
	lda     #0
	sta     cnt
L0005:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp2
	jsr     fold
	inc     cnt
	jne     L0005
; --- decsp3
	lda     #0
	sta     cnt
L0006:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp3
	jsr     fold
	inc     cnt
	jne     L0006
; --- decsp4
	lda     #0
	sta     cnt
L0007:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp4
	jsr     fold
	inc     cnt
	jne     L0007
; --- decsp5
	lda     #0
	sta     cnt
L0008:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp5
	jsr     fold
	inc     cnt
	jne     L0008
; --- decsp6
	lda     #0
	sta     cnt
L0009:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp6
	jsr     fold
	inc     cnt
	jne     L0009
; --- decsp7
	lda     #0
	sta     cnt
L000A:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp7
	jsr     fold
	inc     cnt
	jne     L000A
; --- decsp8
	lda     #0
	sta     cnt
L000B:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     decsp8
	jsr     fold
	inc     cnt
	jne     L000B
; --- incsp1
	lda     #0
	sta     cnt
L000C:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp1
	jsr     fold
	inc     cnt
	jne     L000C
; --- incsp2
	lda     #0
	sta     cnt
L000D:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp2
	jsr     fold
	inc     cnt
	jne     L000D
; --- addysp
	lda     #0
	sta     cnt
L000E:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     addysp
	jsr     fold
	inc     cnt
	jne     L000E
; --- addysp1
	lda     #0
	sta     cnt
L000F:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     addysp1
	jsr     fold
	inc     cnt
	jne     L000F
; --- incsp3
	lda     #0
	sta     cnt
L0010:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp3
	jsr     fold
	inc     cnt
	jne     L0010
; --- incsp4
	lda     #0
	sta     cnt
L0011:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp4
	jsr     fold
	inc     cnt
	jne     L0011
; --- incsp5
	lda     #0
	sta     cnt
L0012:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp5
	jsr     fold
	inc     cnt
	jne     L0012
; --- incsp6
	lda     #0
	sta     cnt
L0013:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp6
	jsr     fold
	inc     cnt
	jne     L0013
; --- incsp7
	lda     #0
	sta     cnt
L0014:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp7
	jsr     fold
	inc     cnt
	jne     L0014
; --- incsp8
	lda     #0
	sta     cnt
L0015:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incsp8
	jsr     fold
	inc     cnt
	jne     L0015
; --- ldaxysp
	lda     #0
	sta     cnt
L0016:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     ldaxysp
	jsr     fold
	inc     cnt
	jne     L0016
; --- ldax0sp
	lda     #0
	sta     cnt
L0017:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     ldax0sp
	jsr     fold
	inc     cnt
	jne     L0017
; --- staxysp
	lda     #0
	sta     cnt
L0018:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     staxysp
	jsr     fold
	inc     cnt
	jne     L0018
; --- stax0sp
	lda     #0
	sta     cnt
L0019:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     stax0sp
	jsr     fold
	inc     cnt
	jne     L0019
; --- pushwysp
	lda     #0
	sta     cnt
L001A:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     pushwysp
	jsr     fold
	inc     cnt
	jne     L001A
; --- pushw0sp
	lda     #0
	sta     cnt
L001B:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     pushw0sp
	jsr     fold
	inc     cnt
	jne     L001B
; --- addeqysp
	lda     #0
	sta     cnt
L001C:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     addeqysp
	jsr     fold
	inc     cnt
	jne     L001C
; --- addeq0sp
	lda     #0
	sta     cnt
L001D:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     addeq0sp
	jsr     fold
	inc     cnt
	jne     L001D
; --- subeqysp
	lda     #0
	sta     cnt
L001E:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     subeqysp
	jsr     fold
	inc     cnt
	jne     L001E
; --- subeq0sp
	lda     #0
	sta     cnt
L001F:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     subeq0sp
	jsr     fold
	inc     cnt
	jne     L001F
; --- leaaxsp
	lda     #0
	sta     cnt
L0020:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     leaaxsp
	jsr     fold
	inc     cnt
	jne     L0020
; --- leaa0sp
	lda     #0
	sta     cnt
L0021:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     leaa0sp
	jsr     fold
	inc     cnt
	jne     L0021
; --- tosicmp
	lda     #0
	sta     cnt
L0022:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     tosicmp
	jsr     fold
	inc     cnt
	jne     L0022
; --- tosicmp0
	lda     #0
	sta     cnt
L0023:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     tosicmp0
	jsr     fold
	inc     cnt
	jne     L0023
; --- incax2
	lda     #0
	sta     cnt
L0024:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax2
	jsr     fold
	inc     cnt
	jne     L0024
; --- incaxy
	lda     #0
	sta     cnt
L0025:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incaxy
	jsr     fold
	inc     cnt
	jne     L0025
; --- incax3
	lda     #0
	sta     cnt
L0026:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax3
	jsr     fold
	inc     cnt
	jne     L0026
; --- incax4
	lda     #0
	sta     cnt
L0027:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax4
	jsr     fold
	inc     cnt
	jne     L0027
; --- incax5
	lda     #0
	sta     cnt
L0028:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax5
	jsr     fold
	inc     cnt
	jne     L0028
; --- incax6
	lda     #0
	sta     cnt
L0029:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax6
	jsr     fold
	inc     cnt
	jne     L0029
; --- incax7
	lda     #0
	sta     cnt
L002A:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax7
	jsr     fold
	inc     cnt
	jne     L002A
; --- incax8
	lda     #0
	sta     cnt
L002B:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     incax8
	jsr     fold
	inc     cnt
	jne     L002B
; --- aslax1
	lda     #0
	sta     cnt
L002C:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     aslax1
	jsr     fold
	inc     cnt
	jne     L002C
; --- shlax1
	lda     #0
	sta     cnt
L002D:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     shlax1
	jsr     fold
	inc     cnt
	jne     L002D
; --- aslax2
	lda     #0
	sta     cnt
L002E:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     aslax2
	jsr     fold
	inc     cnt
	jne     L002E
; --- shlax2
	lda     #0
	sta     cnt
L002F:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     shlax2
	jsr     fold
	inc     cnt
	jne     L002F
; --- mulax3
	lda     #0
	sta     cnt
L0030:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     mulax3
	jsr     fold
	inc     cnt
	jne     L0030
; --- mulax5
	lda     #0
	sta     cnt
L0031:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     mulax5
	jsr     fold
	inc     cnt
	jne     L0031
; --- mulax9
	lda     #0
	sta     cnt
L0032:
	jsr     setup
	lda     cnt
	asl     a
	adc     cnt
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	lda     cnt
	lsr     a
	lda     cnt
	jsr     mulax9
	jsr     fold
	inc     cnt
	jne     L0032
; --- ldaxidx
	lda     #0
	sta     cnt
L0033:
	jsr     setup
	lda     cnt
	and     #31
	clc
	adc     #<buf
	pha
	lda     #0
	adc     #>buf
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	pla
	jsr     ldaxidx
	jsr     fold
	inc     cnt
	jne     L0033
; --- ldaxi
	lda     #0
	sta     cnt
L0034:
	jsr     setup
	lda     cnt
	and     #31
	clc
	adc     #<buf
	pha
	lda     #0
	adc     #>buf
	tax
	lda     cnt
	and     #6
	ora     #1
	tay
	pla
	jsr     ldaxi
	jsr     fold
	inc     cnt
	jne     L0034
; --- staxspidx
	lda     #0
	sta     cnt
L0035:
	jsr     setup
	lda     cnt
	and     #31
	clc
	adc     #<buf
	ldy     #0
	sta     (sp),y
	lda     #0
	adc     #>buf
	iny
	sta     (sp),y
	lda     cnt
	and     #6
	tay
	lda     cnt
	asl     a
	tax
	lda     cnt
	jsr     staxspidx
	jsr     fold
	inc     cnt
	jne     L0035
; --- laddeq
	lda     #0
	sta     cnt
L0036:
	jsr     setup
	lda     cnt
	and     #28
	clc
	adc     #<buf
	sta     ptr1
	lda     #0
	adc     #>buf
	tay
	lda     cnt
	asl     a
	tax
	lda     cnt
	jsr     laddeq
	jsr     fold
	inc     cnt
	jne     L0036
; --- laddeqa
	lda     #0
	sta     cnt
L0037:
	jsr     setup
	lda     cnt
	and     #28
	clc
	adc     #<buf
	sta     ptr1
	lda     #0
	adc     #>buf
	tay
	lda     cnt
	asl     a
	tax
	lda     cnt
	jsr     laddeqa
	jsr     fold
	inc     cnt
	jne     L0037
; --- laddeq1
	lda     #0
	sta     cnt
L0038:
	jsr     setup
	lda     cnt
	and     #28
	clc
	adc     #<buf
	sta     ptr1
	lda     #0
	adc     #>buf
	tay
	lda     cnt
	asl     a
	tax
	lda     cnt
	jsr     laddeq1
	jsr     fold
	inc     cnt
	jne     L0038
; restore the real C stack and print the checksum
	lda	sp0
	sta	sp
	lda	sp0+1
	sta	sp+1
	lda	#<fmt
	ldx	#>fmt
	jsr	pushax
	lda	chk+2
	sta	sreg
	lda	#0
	sta	sreg+1
	lda	chk
	ldx	chk+1
	jsr	pusheax
	ldy	#6
	jsr	_printf
	lda	chk
	and	#$7F
	ldx	#0
	rts
.endproc
