;
; File generated by cc65 v 2.19 - Git b75f872
;
	.fopt		compiler,"cc65 v 2.19 - Git b75f872"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/video.c", 4310, 1789088660
	.dbg		file, "include/video.h", 1295, 1789084506
	.dbg		file, "C:\cc65\include/conio.h", 9026, 1739116317
	.dbg		file, "C:\cc65\include/stdarg.h", 2913, 1739116318
	.dbg		file, "C:\cc65\include/target.h", 3046, 1739116318
	.dbg		file, "C:\cc65\include/cbm.h", 11896, 1739116317
	.dbg		file, "C:\cc65\include/stddef.h", 3037, 1739116318
	.dbg		file, "C:\cc65\include/c64.h", 6989, 1739116317
	.dbg		file, "C:\cc65\include/_vic2.h", 10835, 1739116316
	.dbg		file, "C:\cc65\include/_sid.h", 3626, 1739116316
	.dbg		file, "C:\cc65\include/_6526.h", 3962, 1739116316
	.dbg		file, "C:\cc65\include/cbm_filetype.h", 4949, 1739116317
	.export		_detect_video_system
	.export		_video_name
	.export		_video_get_text_size
	.export		_video_gfx_width
	.export		_video_gfx_height
	.export		_video_colour_count
	.import		_screensize

.segment	"RODATA"

S0003:
	.byte	$CD,$4F,$4E,$4F,$43,$48,$52,$4F,$4D,$45,$00
S0004:
	.byte	$D5,$4E,$4B,$4E,$4F,$57,$4E,$00
S0002:
	.byte	$CE,$D4,$D3,$C3,$00
S0001:
	.byte	$D0,$C1,$CC,$00

; ---------------------------------------------------------------
; enum $anon-enum-0001 __near__ detect_video_system (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_detect_video_system: near

	.dbg	func, "detect_video_system", "00", static, "_detect_video_system"
	.dbg	sym, "max_raster", "00", auto, -2
	.dbg	sym, "i", "00", auto, -4

.segment	"CODE"

;
; unsigned max_raster = 0;
;
	.dbg	line, "src/video.c", 30
	jsr     push0
;
; for (i = 0; i < 1000; ++i)
;
	.dbg	line, "src/video.c", 33
	jsr     decsp2
	ldy     #$00
	tya
	sta     (sp),y
	iny
	sta     (sp),y
L0002:	ldy     #$01
	lda     (sp),y
	cmp     #$03
	bne     L0006
	dey
	lda     (sp),y
	cmp     #$E8
L0006:	bcs     L0003
;
; unsigned char lo = VIC.rasterline;
;
	.dbg	line, "src/video.c", 35
	lda     $D012
	jsr     pusha
;
; unsigned char hi8 = (VIC.ctrl1 & 0x80) ? 1 : 0;
;
	.dbg	line, "src/video.c", 36
	lda     $D011
	and     #$80
	beq     L000D
	lda     #$01
L000D:	jsr     pusha
;
; unsigned current = ((unsigned)hi8 << 8) | lo;
;
	.dbg	line, "src/video.c", 37
	ldy     #$01
	lda     (sp),y
	pha
	dey
	lda     (sp),y
	tax
	pla
	jsr     pushax
;
; if (current > max_raster)
;
	.dbg	line, "src/video.c", 39
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sec
	ldy     #$06
	sbc     (sp),y
	sta     tmp1
	txa
	iny
	sbc     (sp),y
	ora     tmp1
	bcc     L0009
	beq     L0009
;
; max_raster = current;
;
	.dbg	line, "src/video.c", 41
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$06
	jsr     staxysp
;
; }
;
	.dbg	line, "src/video.c", 43
L0009:	jsr     incsp4
;
; for (i = 0; i < 1000; ++i)
;
	.dbg	line, "src/video.c", 33
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0002
;
; return (max_raster > 280) ? VIDEO_PAL : VIDEO_NTSC;
;
	.dbg	line, "src/video.c", 47
L0003:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$19
	txa
	sbc     #$01
	bcc     L000E
	ldx     #$00
	lda     #$01
	jmp     incsp4
L000E:	tya
	ldx     #$00
;
; }
;
	.dbg	line, "src/video.c", 81
	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; const char *__near__ video_name (enum $anon-enum-0001 video)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_video_name: near

	.dbg	func, "video_name", "00", static, "_video_name"
	.dbg	sym, "video", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "src/video.c", 84
	jsr     pusha
;
; switch (video)
;
	.dbg	line, "src/video.c", 85
	ldy     #$00
	lda     (sp),y
;
; }
;
	.dbg	line, "src/video.c", 98
	cmp     #$01
	beq     L0004
	cmp     #$02
	beq     L0005
	cmp     #$03
	beq     L0006
	jmp     L0007
;
; return "PAL";
;
	.dbg	line, "src/video.c", 88
L0004:	lda     #<(S0001)
	ldx     #>(S0001)
	jmp     incsp1
;
; return "NTSC";
;
	.dbg	line, "src/video.c", 91
L0005:	lda     #<(S0002)
	ldx     #>(S0002)
	jmp     incsp1
;
; return "Monochrome";
;
	.dbg	line, "src/video.c", 94
L0006:	lda     #<(S0003)
	ldx     #>(S0003)
	jmp     incsp1
;
; return "Unknown";
;
	.dbg	line, "src/video.c", 97
L0007:	lda     #<(S0004)
	ldx     #>(S0004)
;
; }
;
	.dbg	line, "src/video.c", 99
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ video_get_text_size (unsigned int *cols, unsigned int *rows)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_video_get_text_size: near

	.dbg	func, "video_get_text_size", "00", static, "_video_get_text_size"
	.dbg	sym, "cols", "00", auto, 2
	.dbg	sym, "rows", "00", auto, 0
	.dbg	sym, "c", "00", auto, -1
	.dbg	sym, "r", "00", auto, -2

.segment	"CODE"

;
; {
;
	.dbg	line, "src/video.c", 102
	jsr     pushax
;
; screensize(&c, &r);
;
	.dbg	line, "src/video.c", 105
	jsr     decsp2
	lda     sp
	ldx     sp+1
	clc
	adc     #$01
	bcc     L0002
	inx
L0002:	jsr     pushax
	lda     sp
	ldx     sp+1
	clc
	adc     #$02
	bcc     L0003
	inx
L0003:	jsr     _screensize
;
; *cols = c;
;
	.dbg	line, "src/video.c", 106
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	dey
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; *rows = r;
;
	.dbg	line, "src/video.c", 107
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
;
; }
;
	.dbg	line, "src/video.c", 108
	jmp     incsp6

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned int __near__ video_gfx_width (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_video_gfx_width: near

	.dbg	func, "video_gfx_width", "00", static, "_video_gfx_width"

.segment	"CODE"

;
; return 320;
;
	.dbg	line, "src/video.c", 113
	ldx     #$01
	lda     #$40
;
; }
;
	.dbg	line, "src/video.c", 119
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned int __near__ video_gfx_height (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_video_gfx_height: near

	.dbg	func, "video_gfx_height", "00", static, "_video_gfx_height"

.segment	"CODE"

;
; return 200;
;
	.dbg	line, "src/video.c", 124
	ldx     #$00
	lda     #$C8
;
; }
;
	.dbg	line, "src/video.c", 130
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned int __near__ video_colour_count (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_video_colour_count: near

	.dbg	func, "video_colour_count", "00", static, "_video_colour_count"

.segment	"CODE"

;
; return 16;
;
	.dbg	line, "src/video.c", 135
	ldx     #$00
	lda     #$10
;
; }
;
	.dbg	line, "src/video.c", 143
	rts

	.dbg	line
.endproc

