;
; File generated by cc65 v 2.19 - Git b75f872
;
	.fopt		compiler,"cc65 v 2.19 - Git b75f872"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/main.c", 2740, 1790528730
	.dbg		file, "include/main.h", 1125, 1789089321
	.dbg		file, "C:\cc65\include/stdio.h", 6999, 1739116318
	.dbg		file, "C:\cc65\include/conio.h", 9026, 1739116317
	.dbg		file, "C:\cc65\include/stdarg.h", 2913, 1739116318
	.dbg		file, "C:\cc65\include/target.h", 3046, 1739116318
	.dbg		file, "C:\cc65\include/cbm.h", 11896, 1739116317
	.dbg		file, "C:\cc65\include/stddef.h", 3037, 1739116318
	.dbg		file, "C:\cc65\include/c64.h", 6989, 1739116317
	.dbg		file, "C:\cc65\include/_vic2.h", 10835, 1739116316
	.dbg		file, "C:\cc65\include/_sid.h", 3626, 1739116316
	.dbg		file, "C:\cc65\include/_6526.h", 3962, 1739116316
	.dbg		file, "C:\cc65\include/cbm_filetype.h", 4949, 1739116317
	.dbg		file, "include/machine.h", 1250, 1789084268
	.dbg		file, "include/cpu.h", 2916, 1789086269
	.dbg		file, "include/memory.h", 807, 1789084296
	.dbg		file, "include/video.h", 1295, 1789084506
	.dbg		file, "include/sound.h", 663, 1789084315
	.forceimport	__STARTUP__
	.import		_printf
	.import		_puts
	.import		_clrscr
	.import		_machine_model
	.import		_machine_address_bits
	.import		_machine_word_bits
	.import		_cpu_name
	.import		_cpu_detect_fast_mode
	.import		_cpu_supports_fast_mode
	.import		_cpu_supports_supercpu
	.import		_cpu_fast_mode_description
	.import		_cpu_speed_khz
	.import		_memory_installed_bytes
	.import		_memory_heap_free_bytes
	.import		_detect_video_system
	.import		_video_name
	.import		_video_get_text_size
	.import		_video_gfx_width
	.import		_video_gfx_height
	.import		_video_colour_count
	.import		_sound_chip_name
	.import		_sound_voice_count
	.export		_detect_system
	.export		_main

.segment	"RODATA"

S000E:
	.byte	$C3,$D0,$D5,$20,$C1,$52,$43,$48,$49,$54,$45,$43,$54,$55,$52,$45
	.byte	$20,$20,$20,$3A,$20,$25,$55,$2D,$42,$49,$54,$20,$50,$52,$4F,$43
	.byte	$45,$53,$53,$4F,$52,$0D,$00
S0006:
	.byte	$C3,$4C,$4F,$43,$4B,$20,$D3,$50,$45,$45,$44,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$55,$2E,$25,$30,$33,$55,$20,$CD,$C8,$5A
	.byte	$0D,$00
S0015:
	.byte	$C3,$4F,$4C,$4F,$55,$52,$20,$C3,$41,$50,$41,$42,$49,$4C,$49,$54
	.byte	$59,$20,$20,$3A,$20,$25,$55,$20,$43,$4F,$4C,$4F,$55,$52,$53,$0D
	.byte	$00
S0011:
	.byte	$C6,$52,$45,$45,$20,$C8,$45,$41,$50,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$4C,$55,$20,$42,$59,$54,$45,$53,$0D,$00
S0013:
	.byte	$D4,$45,$58,$54,$20,$D2,$45,$53,$4F,$4C,$55,$54,$49,$4F,$4E,$20
	.byte	$20,$20,$20,$3A,$20,$25,$55,$20,$58,$20,$25,$55,$0D,$00
S0010:
	.byte	$C9,$4E,$53,$54,$41,$4C,$4C,$45,$44,$20,$D2,$C1,$CD,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$4C,$55,$20,$CB,$C2,$0D,$00
S000F:
	.byte	$C1,$44,$44,$52,$45,$53,$53,$20,$C2,$55,$53,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$55,$2D,$42,$49,$54,$0D,$00
S0002:
	.byte	$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D
	.byte	$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$00
S0001:
	.byte	$C3,$CF,$CD,$CD,$CF,$C4,$CF,$D2,$C5,$20,$D3,$D9,$D3,$D4,$C5,$CD
	.byte	$20,$C9,$CE,$C6,$CF,$D2,$CD,$C1,$D4,$C9,$CF,$CE,$00
S0014:
	.byte	$C7,$52,$41,$50,$48,$49,$43,$53,$20,$D2,$45,$53,$4F,$4C,$55,$54
	.byte	$49,$4F,$4E,$3A,$20,$25,$55,$58,$25,$55,$0D,$00
S0016:
	.byte	$D3,$4F,$55,$4E,$44,$20,$C8,$41,$52,$44,$57,$41,$52,$45,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$53,$0D,$00
S000D:
	.byte	$C6,$41,$53,$54,$20,$CD,$4F,$44,$45,$20,$C8,$41,$52,$44,$57,$41
	.byte	$52,$45,$20,$3A,$20,$25,$53,$0D,$00
S0017:
	.byte	$D3,$4F,$55,$4E,$44,$20,$D6,$4F,$49,$43,$45,$53,$20,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$55,$0D,$00
S0004:
	.byte	$CD,$4F,$44,$45,$4C,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$53,$0D,$00
S0007:
	.byte	$D3,$55,$50,$45,$52,$C3,$D0,$D5,$20,$C5,$4E,$41,$42,$4C,$45,$44
	.byte	$20,$20,$20,$3A,$20,$25,$53,$0D,$00
S0005:
	.byte	$C3,$D0,$D5,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$53,$0D,$00
S0012:
	.byte	$D6,$49,$44,$45,$4F,$20,$D3,$54,$41,$4E,$44,$41,$52,$44,$20,$20
	.byte	$20,$20,$20,$3A,$20,$25,$53,$0D,$00
S000A:
	.byte	$D3,$55,$50,$50,$4F,$52,$54,$53,$20,$C6,$41,$53,$54,$20,$CD,$4F
	.byte	$44,$45,$20,$3A,$20,$25,$53,$0D,$00
S000B:
	.byte	$D9,$C5,$D3,$00
S0008	:=	S000B+0
S000C:
	.byte	$CE,$CF,$00
S0009	:=	S000C+0
S0003	:=	S000E+38

; ---------------------------------------------------------------
; void __near__ detect_system (struct $anon-struct-000E *info)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_detect_system: near

	.dbg	func, "detect_system", "00", static, "_detect_system"
	.dbg	sym, "info", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "src/main.c", 8
	jsr     pushax
;
; info->model         = machine_model();
;
	.dbg	line, "src/main.c", 9
	jsr     pushw0sp
	jsr     _machine_model
	ldy     #$00
	jsr     staxspidx
;
; info->address_bits  = machine_address_bits();
;
	.dbg	line, "src/main.c", 10
	jsr     pushw0sp
	jsr     _machine_address_bits
	ldy     #$12
	jsr     staxspidx
;
; info->word_bits     = machine_word_bits();
;
	.dbg	line, "src/main.c", 11
	jsr     pushw0sp
	jsr     _machine_word_bits
	ldy     #$14
	jsr     staxspidx
;
; info->cpu           = cpu_name();
;
	.dbg	line, "src/main.c", 13
	jsr     pushw0sp
	jsr     _cpu_name
	ldy     #$02
	jsr     staxspidx
;
; cpu_detect_fast_mode();
;
	.dbg	line, "src/main.c", 17
	jsr     _cpu_detect_fast_mode
;
; info->fast_mode_supported   = cpu_supports_fast_mode();
;
	.dbg	line, "src/main.c", 18
	jsr     pushw0sp
	jsr     _cpu_supports_fast_mode
	ldy     #$0C
	jsr     staxspidx
;
; info->fast_mode_description = cpu_fast_mode_description();
;
	.dbg	line, "src/main.c", 19
	jsr     pushw0sp
	jsr     _cpu_fast_mode_description
	ldy     #$0E
	jsr     staxspidx
;
; info->supercpu_enabled      = cpu_supports_supercpu();
;
	.dbg	line, "src/main.c", 20
	jsr     pushw0sp
	jsr     _cpu_supports_supercpu
	ldy     #$10
	jsr     staxspidx
;
; info->cpu_khz       = cpu_speed_khz();
;
	.dbg	line, "src/main.c", 21
	jsr     pushw0sp
	jsr     _cpu_speed_khz
	ldy     #$08
	jsr     staxspidx
;
; info->ram_installed_bytes = memory_installed_bytes();
;
	.dbg	line, "src/main.c", 23
	jsr     pushw0sp
	jsr     _memory_installed_bytes
	ldy     #$16
	jsr     steaxspidx
;
; info->ram_heap_free_bytes = memory_heap_free_bytes();
;
	.dbg	line, "src/main.c", 24
	jsr     pushw0sp
	jsr     _memory_heap_free_bytes
	ldy     #$1A
	jsr     steaxspidx
;
; info->video          = video_name(detect_video_system());
;
	.dbg	line, "src/main.c", 26
	jsr     pushw0sp
	jsr     _detect_video_system
	jsr     _video_name
	ldy     #$04
	jsr     staxspidx
;
; video_get_text_size(&info->text_cols, &info->text_rows);
;
	.dbg	line, "src/main.c", 27
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$1E
	bcc     L0002
	inx
L0002:	jsr     pushax
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$20
	bcc     L0003
	inx
L0003:	jsr     _video_get_text_size
;
; info->gfx_width      = video_gfx_width();
;
	.dbg	line, "src/main.c", 28
	jsr     pushw0sp
	jsr     _video_gfx_width
	ldy     #$24
	jsr     staxspidx
;
; info->gfx_height     = video_gfx_height();
;
	.dbg	line, "src/main.c", 29
	jsr     pushw0sp
	jsr     _video_gfx_height
	ldy     #$22
	jsr     staxspidx
;
; info->colours        = video_colour_count();
;
	.dbg	line, "src/main.c", 30
	jsr     pushw0sp
	jsr     _video_colour_count
	ldy     #$26
	jsr     staxspidx
;
; info->sound_chip     = sound_chip_name();
;
	.dbg	line, "src/main.c", 32
	jsr     pushw0sp
	jsr     _sound_chip_name
	ldy     #$06
	jsr     staxspidx
;
; info->sound_voices   = sound_voice_count();
;
	.dbg	line, "src/main.c", 33
	jsr     pushw0sp
	jsr     _sound_voice_count
	ldy     #$0A
	jsr     staxspidx
;
; }
;
	.dbg	line, "src/main.c", 34
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

;
; detect_system(&sys);
;
	.dbg	line, "src/main.c", 40
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     _detect_system
;
; clrscr();
;
	.dbg	line, "src/main.c", 42
	jsr     _clrscr
;
; puts("COMMODORE SYSTEM INFORMATION");
;
	.dbg	line, "src/main.c", 43
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _puts
;
; puts("============================");
;
	.dbg	line, "src/main.c", 44
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _puts
;
; puts("");
;
	.dbg	line, "src/main.c", 45
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     _puts
;
; printf("Model              : %s\n", sys.model);
;
	.dbg	line, "src/main.c", 47
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("CPU                : %s\n", sys.cpu);
;
	.dbg	line, "src/main.c", 48
	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     pushax
	lda     M0001+2
	ldx     M0001+2+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Clock Speed        : %u.%03u MHz\n", sys.cpu_khz / 1000, sys.cpu_khz % 1000);
;
	.dbg	line, "src/main.c", 49
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     pushax
	lda     M0001+8
	ldx     M0001+8+1
	jsr     pushax
	ldx     #$03
	lda     #$E8
	jsr     tosudivax
	jsr     pushax
	lda     M0001+8
	ldx     M0001+8+1
	jsr     pushax
	ldx     #$03
	lda     #$E8
	jsr     tosumodax
	jsr     pushax
	ldy     #$06
	jsr     _printf
;
; printf("SuperCPU Enabled   : %s\n", sys.supercpu_enabled ? "YES" : "NO");
;
	.dbg	line, "src/main.c", 50
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     pushax
	lda     M0001+16
	ora     M0001+16+1
	beq     L0002
	lda     #<(S0008)
	ldx     #>(S0008)
	jmp     L0003
L0002:	lda     #<(S0009)
	ldx     #>(S0009)
L0003:	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Supports Fast Mode : %s\n", sys.fast_mode_supported ? "YES" : "NO");
;
	.dbg	line, "src/main.c", 51
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     pushax
	lda     M0001+12
	ora     M0001+12+1
	beq     L0004
	lda     #<(S000B)
	ldx     #>(S000B)
	jmp     L0005
L0004:	lda     #<(S000C)
	ldx     #>(S000C)
L0005:	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Fast Mode Hardware : %s\n", sys.fast_mode_description);
;
	.dbg	line, "src/main.c", 52
	lda     #<(S000D)
	ldx     #>(S000D)
	jsr     pushax
	lda     M0001+14
	ldx     M0001+14+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("CPU Architecture   : %u-bit processor\n", sys.word_bits);
;
	.dbg	line, "src/main.c", 53
	lda     #<(S000E)
	ldx     #>(S000E)
	jsr     pushax
	lda     M0001+20
	ldx     M0001+20+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Address Bus        : %u-bit\n", sys.address_bits);
;
	.dbg	line, "src/main.c", 54
	lda     #<(S000F)
	ldx     #>(S000F)
	jsr     pushax
	lda     M0001+18
	ldx     M0001+18+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Installed RAM      : %lu KB\n", sys.ram_installed_bytes / 1024);
;
	.dbg	line, "src/main.c", 55
	lda     #<(S0010)
	ldx     #>(S0010)
	jsr     pushax
	lda     M0001+22+3
	sta     sreg+1
	lda     M0001+22+2
	sta     sreg
	lda     M0001+22+1
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	ldy     #$00
	sty     sreg+1
	jsr     shreax2
	jsr     pusheax
	ldy     #$06
	jsr     _printf
;
; printf("Free Heap          : %lu bytes\n", sys.ram_heap_free_bytes);
;
	.dbg	line, "src/main.c", 56
	lda     #<(S0011)
	ldx     #>(S0011)
	jsr     pushax
	lda     M0001+26+3
	sta     sreg+1
	lda     M0001+26+2
	sta     sreg
	ldx     M0001+26+1
	lda     M0001+26
	jsr     pusheax
	ldy     #$06
	jsr     _printf
;
; printf("Video Standard     : %s\n", sys.video);
;
	.dbg	line, "src/main.c", 58
	lda     #<(S0012)
	ldx     #>(S0012)
	jsr     pushax
	lda     M0001+4
	ldx     M0001+4+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Text Resolution    : %u x %u\n", sys.text_cols, sys.text_rows);
;
	.dbg	line, "src/main.c", 59
	lda     #<(S0013)
	ldx     #>(S0013)
	jsr     pushax
	lda     M0001+30
	ldx     M0001+30+1
	jsr     pushax
	lda     M0001+32
	ldx     M0001+32+1
	jsr     pushax
	ldy     #$06
	jsr     _printf
;
; printf("Graphics Resolution: %ux%u\n", sys.gfx_width, sys.gfx_height);
;
	.dbg	line, "src/main.c", 60
	lda     #<(S0014)
	ldx     #>(S0014)
	jsr     pushax
	lda     M0001+36
	ldx     M0001+36+1
	jsr     pushax
	lda     M0001+34
	ldx     M0001+34+1
	jsr     pushax
	ldy     #$06
	jsr     _printf
;
; printf("Colour Capability  : %u colours\n", sys.colours);
;
	.dbg	line, "src/main.c", 61
	lda     #<(S0015)
	ldx     #>(S0015)
	jsr     pushax
	lda     M0001+38
	ldx     M0001+38+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Sound Hardware     : %s\n", sys.sound_chip);
;
	.dbg	line, "src/main.c", 63
	lda     #<(S0016)
	ldx     #>(S0016)
	jsr     pushax
	lda     M0001+6
	ldx     M0001+6+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("Sound Voices       : %u\n", sys.sound_voices);
;
	.dbg	line, "src/main.c", 64
	lda     #<(S0017)
	ldx     #>(S0017)
	jsr     pushax
	lda     M0001+10
	ldx     M0001+10+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; return 0;
;
	.dbg	line, "src/main.c", 66
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "src/main.c", 67
	rts

	.dbg	line
.segment	"BSS"

M0001:
	.res	40,$00

.endproc

